Web/Controllers/RecherchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Model;
using Web.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Globalization;
using System.Text;

namespace Web.Controllers
{
    public class RecherchesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: 
        public ActionResult Index()
        {
            ViewBag.ListTypeAnimaux = db.TypeAnimaux.ToList();
            return View(db.Recherche.Where(f => f.Desactiver == false).ToList());
        }

        // GET: Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recherche recherche = db.Recherche.Find(id);
            if (recherche == null)
            {
                return HttpNotFound();
            }
            return View(recherche);
        }

        // GET: Create
        [Authorize(Roles = "Membre, Admin")]
        public ActionResult Create()
        {
            IEnumerable<SelectListItem> List = db.TypeAnimaux.Select(c => new SelectListItem { Text = c.Nom, Value = c.Id.ToString() }).ToList();
            RechercheViewModel model = new RechercheViewModel { ListTypeAnimaux = List };
            return View(model);
        }

        // POST: Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Membre, Admin")]
        public ActionResult Create(RechercheViewModel model, HttpPostedFileBase file)
        {
            Random rnd = new Random();
            ApplicationUser user = db.Users.Find(User.Identity.GetUserId());
            DateTime date = DateTime.Now;
            TypeAnimaux type = db.TypeAnimaux.Find(model.SelectedTypeAnimaux);

            // Upload des images
            List<Image> images = new List<Image>();
            if (file.ContentLength > 0)
            {
                // Supprime les accents du nom du fichier
                string _name = Path.GetFileName(file.FileName);
                //String _FileName = rnd.Next(1, 9999999).ToString();
                String _FileName = ((Int32)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds).ToString();
                _FileName += Path.GetExtension(_name);

                string _path = Path.Combine(Server.MapPath("~/Content/UploadedFiles"), _FileName);
                file.SaveAs(_path);
                Image image = new Image();
                image.Url = "Content/UploadedFiles/" + _FileName;
                images.Add(image);
            }

            Recherche recherche = new Recherche
            {
                Nom = model.Nom,
                Description = model.Description,
                Sexe = model.Sexe,
                Race = model.Race,
                Adresse = model.Adresse,
                Date_ajout = date,
                Date_recherche = model.Date_recherche,
                User = user,
                Images = images,
                Type = type
            };

            if (ModelState.IsValid)
            {
                db.Recherche.Add(recherche);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recherche);
        }

        // GET: Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recherche recherche = db.Recherche.Find(id);
            if (recherche == null)
            {
                return HttpNotFound();
            }
            RechercheViewModel model = new RechercheViewModel
            {
                Id = id,
                Adresse = recherche.Adresse,
                Description = recherche.Description,
                Date_recherche = recherche.Date_recherche,
                Nom = recherche.Nom,
                Race = recherche.Race,
                Sexe = recherche.Sexe,
                ListTypeAnimaux = db.TypeAnimaux.Select(c => new SelectListItem { Text = c.Nom, Value = c.Id.ToString() }).ToList(),
                SelectedTypeAnimaux = recherche.Type.Id
            };
            return View(model);
        }

        // POST: Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RechercheViewModel model)
        {
            if (ModelState.IsValid)
            {
                var originalRecherche = db.Recherche.Find(model.Id);

                if (originalRecherche != null)
                {
                    TypeAnimaux type = db.TypeAnimaux.Find(model.SelectedTypeAnimaux);

                    originalRecherche.Nom = model.Nom;
                    originalRecherche.Description = model.Description;
                    originalRecherche.Sexe = model.Sexe;
                    originalRecherche.Race = model.Race;
                    originalRecherche.Adresse = model.Adresse;
                    originalRecherche.Type = type;
                    originalRecherche.Desactiver = model.Desactiver;
                    originalRecherche.Trouver = model.Trouver;

                    //db.Entry(originalRecherche).CurrentValues.SetValues(updateRecherche);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                //db.Entry(recherche).State = EntityState.Modified;
                //db.SaveChanges();
            }
            return View(model);
        }

        // GET: Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recherche recherche = db.Recherche.Find(id);
            if (recherche == null)
            {
                return HttpNotFound();
            }
            return View(recherche);
        }

        // POST: Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recherche recherche = db.Recherche.Find(id);
            db.Recherche.Remove(recherche);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Views/Recherches/Create.cshtml
@model Web.Models.RechercheViewModel
@using Web.Model

@{
    ViewBag.Title = "Create";
}
<div class="row title">
    <h2>Signaler une disparition</h2>
</div>
<div class="row retour">
    <a href="@Url.Action("Index")" class="btn btn-primary pull-right"><i class="fa fa-caret-left"></i>Retourner à la liste</a>
</div>
<div class="row">
    @using (Html.BeginForm("Create", "Recherches", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.SelectedTypeAnimaux, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SelectedTypeAnimaux, Model.ListTypeAnimaux, "Choisir une catégorie ...", new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sexe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sexe, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Race, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Race, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Race, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.Date_recherche, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date_recherche, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date_recherche, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("file", "", new { type = "file" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Valider" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Recherches/Delete.cshtml
@model Web.Model.Recherche

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recherche</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Actif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trouver)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trouver)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_recherche)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_recherche)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_ajout)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_ajout)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/Recherches/Details.cshtml
@model Web.Model.Recherche
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
}

<div class="details">
    <div class="row title">
        <h2>@Html.DisplayFor(model => model.Nom)</h2>
        <p></p>
    </div>
    <div class="row retour">
        @if (User.Identity.IsAuthenticated && User.Identity.GetUserId().Equals(Model.User.Id))
        {
            <a href="@Url.Action("Edit", new { id = Model.Id })" class="btn btn-primary pull-right" style="margin-left: 15px"><i class="fa fa-pencil"></i>Editer</a>
        }
        <a href="@Url.Action("Index")" class="btn btn-primary pull-right"><i class="fa fa-caret-left"></i>Retourner à la liste</a>
    </div>
    <div class="row">
        <div class="col-sm-4">
            @if (Model.Images.Count == 0)
            {
                <img src="https://cdn.shopify.com/s/files/1/0889/1092/products/1T9A3294.jpg?v=1435149577" alt="image" class="border-tlr-radius">
            }
            else
            {
                <img src="../../@Model.Images[0].Url" alt="image" class="border-tlr-radius">
            }
        </div>
        <div class="col-sm-8">
            <p><strong>@Html.DisplayNameFor(model => model.Description) :</strong> @Html.DisplayFor(model => model.Description)</p>
            <p><strong>@Html.DisplayNameFor(model => model.Sexe) :</strong> @Html.DisplayFor(model => model.Sexe)</p>
            <p><strong>@Html.DisplayNameFor(model => model.Race) :</strong> @Html.DisplayFor(model => model.Race)</p>
            <p><strong>@Html.DisplayNameFor(model => model.Adresse) :</strong> <span id="address">@Html.DisplayFor(model => model.Adresse)</span></p>
            <p><strong>Date de la disparition :</strong> @Model.Date_recherche.ToString("dd/MM/yyyy")</p>
        </div>
    </div>
    <div class="row">
        <div id="google-map"></div>
    </div>
</div>

@section scripts {
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2jdcLopDIPzfN0R2VFlfqQBh2VNP--ig&callback=init_maps"></script>
}

Web/Views/Recherches/Edit.cshtml
@model Web.Models.RechercheViewModel
@using Web.Model

@{
    ViewBag.Title = "Edit";
}

<div class="row title">
    <h2>Modifier</h2>
</div>
<div class="row retour">
    <a href="@Url.Action("Index")" class="btn btn-primary pull-right"><i class="fa fa-caret-left"></i>Retourner à la liste</a>
</div>
<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.SelectedTypeAnimaux, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SelectedTypeAnimaux, Model.ListTypeAnimaux, "Choisir une catégorie ...", new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sexe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sexe, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Race, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Race, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Race, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Desactiver, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Desactiver)
                        @Html.ValidationMessageFor(model => model.Desactiver, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trouver, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Trouver)
                        @Html.ValidationMessageFor(model => model.Trouver, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.Date_recherche, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date_recherche, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date_recherche, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Valider" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Web/Views/Recherches/Index.cshtml
@model IEnumerable<Web.Model.Recherche>

@{
    ViewBag.Title = "Index";
}

<div class="row search">
    <div class="col-sm-4">
        <form>
            <div class="form-group">
                <label>Recherche par adresse: </label>
                <div class="input-group">
                    <input type="text" name="serach-google-map" id="inputSearchGoogleMap"
                           placeholder="Fitrer par adresse" class="form-control" />
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="btSeachGoogleMap">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <input type="button" value="Supprimer les marqueurs" id="resetMarker" class="btn btn-default" style="margin-top: 10px;"/>
            </div>
            <div class="form-group">
                <label>Recherche par type d'animaux : </label>
                @Html.DropDownList("typeAnimaux", new SelectList(ViewBag.ListTypeAnimaux, "Id", "Nom"), 
               "Choisir une catégorie ...", new { @class = "form-control" })
            </div>
        </form>
    </div>
    <div class="col-sm-8">
        <div class="row">
            <div id="recherche-google-map" style="height: 300px;"></div>
        </div>
    </div>
</div>

@if (User.Identity.IsAuthenticated)
{
    <div class="row retour">
        <a href="@Url.Action("Create")" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>Ajouter</a>
    </div>
} 

<div class="row result">
    @foreach (var item in Model){
        <div class="col-sm-3" data-id="@item.Type.Id" data-address="@item.Adresse">
            <div class="card radius shadowDepth1">
                <div class="card__image border-tlr-radius">
                    @if (item.Images.Count == 0)
                    {
                        <span style=""></span>
                        <img src="https://cdn.shopify.com/s/files/1/0889/1092/products/1T9A3294.jpg?v=1435149577" alt="image" class="border-tlr-radius">
                    }
                    else
                    {
                        <span style="background: url('../@item.Images[0].Url') top center; background-size: cover; display: block; height: 250px; width: 100%"></span>
                        @*<img src="../@item.Images[0].Url" alt="image" class="border-tlr-radius">*@
                    }
                    
                </div>
                <div class="card__content card__padding">
                    <div class="card__share">
                        <a id="share" class="share-toggle share-icon" href="@Url.Action("Details", new { id = item.Id })"></a>
                    </div>
                    <div class="card__meta">
                        <time>@item.Date_ajout.ToString("dd/MM/yyyy")</time>
                    </div>

                    <article class="card__article">
                        <h3>@Html.DisplayFor(modelItem => item.Nom)</h3>
                        <p>@Html.DisplayFor(modelItem => item.Description)</p>
                    </article>
                </div>
            </div>
        </div>
    }
</div>

@section scripts {
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2jdcLopDIPzfN0R2VFlfqQBh2VNP--ig&callback=init_maps_recherche"></script>
}